apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
  labels:
    app: test2
spec:
  replicas: 1
  revisionHistoryLimit: 10
  minReadySeconds: 5
  selector:
    matchLabels:
      app: test2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: test2
        tier: service
    spec:
      containers:
      - name: test2
        image: "okcan/test2:1.1"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: test2
  labels:
    app: test2
    tier: service
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: test2
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test2
  labels:
    app: test2
    tier: backend
spec:
  backend:
    serviceName: test2
    servicePort: 8080
